@startuml
annotation java.lang.SuppressWarnings
class Interface.PN_Balikan
class Interface.PN_DetX2
class Interface.PN_DetX3
class Interface.PN_MatriksX2
class Interface.PN_MatriksX3
class Interface.PN_SPL
class Interface.PN_Transpose
class Main.Main
class Main.PN_About
class java.awt.Dimension
class java.awt.Toolkit
class javax.swing.JFrame
class javax.swing.JOptionPane
class javax.swing.JPanel
Main.Main ..> java.lang.SuppressWarnings
Main.Main ..> Interface.PN_Balikan
Main.Main ..> Interface.PN_DetX2
Main.Main ..> Interface.PN_DetX3
Main.Main ..> Interface.PN_MatriksX2
Main.Main ..> Interface.PN_MatriksX3
Main.Main ..> Interface.PN_SPL
Main.Main ..> Interface.PN_Transpose
Main.Main ..> java.awt.Dimension
Main.Main ..> java.awt.Toolkit
Main.Main --|> javax.swing.JFrame
Main.Main ..> javax.swing.JOptionPane
Main.PN_About ..> java.lang.SuppressWarnings
Main.PN_About --|> javax.swing.JPanel
@enduml