/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

/**
 *
 * @author zero
 */
public class X3 extends javax.swing.JPanel {

    /**
     * Creates new form X2
     */
    public X3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MatrixA = new javax.swing.JPanel();
        A11 = new javax.swing.JTextField();
        A31 = new javax.swing.JTextField();
        A33 = new javax.swing.JTextField();
        A12 = new javax.swing.JTextField();
        A21 = new javax.swing.JTextField();
        A22 = new javax.swing.JTextField();
        A13 = new javax.swing.JTextField();
        A23 = new javax.swing.JTextField();
        A32 = new javax.swing.JTextField();
        LB_matrixA = new javax.swing.JLabel();
        LB_matrixB = new javax.swing.JLabel();
        OP_choese = new javax.swing.JLabel();
        OP_penjumahan = new javax.swing.JRadioButton();
        OP_pengurangan = new javax.swing.JRadioButton();
        LB_hasil = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        MatrixA1 = new javax.swing.JPanel();
        A14 = new javax.swing.JTextField();
        A34 = new javax.swing.JTextField();
        A35 = new javax.swing.JTextField();
        A15 = new javax.swing.JTextField();
        A24 = new javax.swing.JTextField();
        A25 = new javax.swing.JTextField();
        A16 = new javax.swing.JTextField();
        A26 = new javax.swing.JTextField();
        A36 = new javax.swing.JTextField();
        MatrixA2 = new javax.swing.JPanel();
        A17 = new javax.swing.JTextField();
        A37 = new javax.swing.JTextField();
        A38 = new javax.swing.JTextField();
        A18 = new javax.swing.JTextField();
        A27 = new javax.swing.JTextField();
        A28 = new javax.swing.JTextField();
        A19 = new javax.swing.JTextField();
        A29 = new javax.swing.JTextField();
        A39 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(518, 530));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout MatrixALayout = new javax.swing.GroupLayout(MatrixA);
        MatrixA.setLayout(MatrixALayout);
        MatrixALayout.setHorizontalGroup(
            MatrixALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrixALayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(MatrixALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A21, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A31, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrixALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A22, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrixALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A13)
                    .addComponent(A23, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A32, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(16, 16, 16))
        );
        MatrixALayout.setVerticalGroup(
            MatrixALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrixALayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(MatrixALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A13)
                    .addGroup(MatrixALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(A11)
                        .addComponent(A12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrixALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A22)
                    .addComponent(A21)
                    .addComponent(A23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrixALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A31)
                    .addComponent(A33)
                    .addComponent(A32))
                .addGap(13, 13, 13))
        );

        LB_matrixA.setText("Matrix A");

        LB_matrixB.setText("Matrix B");

        OP_choese.setText("Pilih Operasi yang akan di lakukan");

        OP_penjumahan.setText("Penjumlahan");
        OP_penjumahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OP_penjumahanActionPerformed(evt);
            }
        });

        OP_pengurangan.setText("Pengurangan");
        OP_pengurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OP_penguranganActionPerformed(evt);
            }
        });

        LB_hasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_hasil.setText("Hasil");

        jToggleButton1.setBackground(new java.awt.Color(0, 153, 102));
        jToggleButton1.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButton1.setText("Hitung");

        javax.swing.GroupLayout MatrixA1Layout = new javax.swing.GroupLayout(MatrixA1);
        MatrixA1.setLayout(MatrixA1Layout);
        MatrixA1Layout.setHorizontalGroup(
            MatrixA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrixA1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(MatrixA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A24, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A34, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrixA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A25, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrixA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A16)
                    .addComponent(A26, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A36, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(16, 16, 16))
        );
        MatrixA1Layout.setVerticalGroup(
            MatrixA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrixA1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(MatrixA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A16)
                    .addGroup(MatrixA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(A14)
                        .addComponent(A15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrixA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A25)
                    .addComponent(A24)
                    .addComponent(A26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrixA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A34)
                    .addComponent(A35)
                    .addComponent(A36))
                .addContainerGap())
        );

        javax.swing.GroupLayout MatrixA2Layout = new javax.swing.GroupLayout(MatrixA2);
        MatrixA2.setLayout(MatrixA2Layout);
        MatrixA2Layout.setHorizontalGroup(
            MatrixA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrixA2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(MatrixA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(A37, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrixA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(A18, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrixA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(A19, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(A29, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A39, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(16, 16, 16))
        );
        MatrixA2Layout.setVerticalGroup(
            MatrixA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatrixA2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(MatrixA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A19)
                    .addGroup(MatrixA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(A17)
                        .addComponent(A18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrixA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A28)
                    .addComponent(A27)
                    .addComponent(A29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MatrixA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A37)
                    .addComponent(A38)
                    .addComponent(A39))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_hasil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(MatrixA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LB_matrixA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(143, 143, 143)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LB_matrixB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(196, 196, 196))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(MatrixA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OP_penjumahan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OP_pengurangan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OP_choese, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MatrixA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_matrixA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LB_matrixB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MatrixA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatrixA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(OP_choese, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OP_penjumahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OP_pengurangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LB_hasil, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MatrixA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(195, 195, 195))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void OP_penjumahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OP_penjumahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OP_penjumahanActionPerformed

    private void OP_penguranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OP_penguranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OP_penguranganActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A11;
    private javax.swing.JTextField A12;
    private javax.swing.JTextField A13;
    private javax.swing.JTextField A14;
    private javax.swing.JTextField A15;
    private javax.swing.JTextField A16;
    private javax.swing.JTextField A17;
    private javax.swing.JTextField A18;
    private javax.swing.JTextField A19;
    private javax.swing.JTextField A21;
    private javax.swing.JTextField A22;
    private javax.swing.JTextField A23;
    private javax.swing.JTextField A24;
    private javax.swing.JTextField A25;
    private javax.swing.JTextField A26;
    private javax.swing.JTextField A27;
    private javax.swing.JTextField A28;
    private javax.swing.JTextField A29;
    private javax.swing.JTextField A31;
    private javax.swing.JTextField A32;
    private javax.swing.JTextField A33;
    private javax.swing.JTextField A34;
    private javax.swing.JTextField A35;
    private javax.swing.JTextField A36;
    private javax.swing.JTextField A37;
    private javax.swing.JTextField A38;
    private javax.swing.JTextField A39;
    private javax.swing.JLabel LB_hasil;
    private javax.swing.JLabel LB_matrixA;
    private javax.swing.JLabel LB_matrixB;
    private javax.swing.JPanel MatrixA;
    private javax.swing.JPanel MatrixA1;
    private javax.swing.JPanel MatrixA2;
    private javax.swing.JLabel OP_choese;
    private javax.swing.JRadioButton OP_pengurangan;
    private javax.swing.JRadioButton OP_penjumahan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
