/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Interface.Balikan;
import Interface.DetX2;
import Interface.Transpose;
import Interface.X2;
import Interface.X3;
import javax.swing.JOptionPane;




/**
 *
 * @author zero
 */
public class MatrixCalc extends javax.swing.JFrame {

    /**
     * Creates new form MatrixCalc
     */
    public MatrixCalc() {
        setTitle("Matrix Calculator");
        initComponents();
        
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pn_Sidebar = new javax.swing.JPanel();
        Pn_menu = new javax.swing.JPanel();
        Lb_Title = new javax.swing.JLabel();
        Transpose = new javax.swing.JToggleButton();
        balikan = new javax.swing.JToggleButton();
        Determinan = new javax.swing.JToggleButton();
        PenjumlahanPengurangan = new javax.swing.JToggleButton();
        SPL = new javax.swing.JToggleButton();
        Pn_Main = new javax.swing.JPanel();
        Pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        Pn_Sidebar.setPreferredSize(new java.awt.Dimension(280, 600));
        Pn_Sidebar.setLayout(new javax.swing.BoxLayout(Pn_Sidebar, javax.swing.BoxLayout.LINE_AXIS));

        Lb_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_Title.setText("Aljabar Geometri");

        Transpose.setText("Transpose");
        Transpose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransposeMouseClicked(evt);
            }
        });

        balikan.setText("Balikan");
        balikan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balikanMouseClicked(evt);
            }
        });

        Determinan.setText("Determinan");
        Determinan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeterminanMouseClicked(evt);
            }
        });

        PenjumlahanPengurangan.setText("Penjumlahan & Pengurangan");
        PenjumlahanPengurangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PenjumlahanPenguranganMouseClicked(evt);
            }
        });

        SPL.setText("Solusi Persamaan Linear");
        SPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pn_menuLayout = new javax.swing.GroupLayout(Pn_menu);
        Pn_menu.setLayout(Pn_menuLayout);
        Pn_menuLayout.setHorizontalGroup(
            Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_menuLayout.createSequentialGroup()
                .addGroup(Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pn_menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lb_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pn_menuLayout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addGroup(Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Transpose, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(balikan, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(Determinan, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(PenjumlahanPengurangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SPL, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        Pn_menuLayout.setVerticalGroup(
            Pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PenjumlahanPengurangan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Transpose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balikan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Determinan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPL)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        Pn_Sidebar.add(Pn_menu);

        jPanel1.add(Pn_Sidebar, java.awt.BorderLayout.LINE_START);

        Pn_Main.setMaximumSize(new java.awt.Dimension(32767, 40000));

        Pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout Pn_MainLayout = new javax.swing.GroupLayout(Pn_Main);
        Pn_Main.setLayout(Pn_MainLayout);
        Pn_MainLayout.setHorizontalGroup(
            Pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_MainLayout.createSequentialGroup()
                .addComponent(Pn_utama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(518, 518, 518))
        );
        Pn_MainLayout.setVerticalGroup(
            Pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pn_MainLayout.createSequentialGroup()
                .addComponent(Pn_utama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 530, Short.MAX_VALUE))
        );

        jPanel1.add(Pn_Main, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        Pn_utama.add(new Home());
        Pn_utama.repaint();
        Pn_utama.revalidate();   
        
    }//GEN-LAST:event_formWindowOpened

    private void PenjumlahanPenguranganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PenjumlahanPenguranganMouseClicked
        // TODO add your handling code here:
        String menu= JOptionPane.showInputDialog("Pilih Ordo \n1- 2 X 2 \n2- 3 X 3");
        int chose=Integer.parseInt(menu);
        
        switch (chose) {
            case 1:
                Pn_utama.removeAll();
                Pn_utama.add(new X2());
                Pn_utama.repaint();
                Pn_utama.revalidate();
                break;
            case 2 : 
                Pn_utama.removeAll();
                Pn_utama.add(new X3());
                Pn_utama.repaint();
                Pn_utama.revalidate();
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_PenjumlahanPenguranganMouseClicked

    private void SPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPLActionPerformed

    private void TransposeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransposeMouseClicked
        // TODO add your handling code here:
        Pn_utama.removeAll();
        Pn_utama.add(new Transpose());
        Pn_utama.repaint();
        Pn_utama.revalidate();
    }//GEN-LAST:event_TransposeMouseClicked

    private void balikanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balikanMouseClicked
        // TODO add your handling code here:
        Pn_utama.removeAll();
        Pn_utama.add(new Balikan());
        Pn_utama.repaint();
        Pn_utama.revalidate();
    }//GEN-LAST:event_balikanMouseClicked

    private void DeterminanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeterminanMouseClicked
        // TODO add your handling code here:
        String menu= JOptionPane.showInputDialog("Pilih Ordo \n1- 2 X 2 \n2- 3 X 3");
        int chose=Integer.parseInt(menu);
        
        switch (chose) {
            case 1:
                Pn_utama.removeAll();
                Pn_utama.add(new DetX2());
                Pn_utama.repaint();
                Pn_utama.revalidate();
                break;
            default:
                throw new AssertionError();
        }
        
    }//GEN-LAST:event_DeterminanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatrixCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatrixCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatrixCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatrixCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatrixCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Determinan;
    private javax.swing.JLabel Lb_Title;
    private javax.swing.JToggleButton PenjumlahanPengurangan;
    private javax.swing.JPanel Pn_Main;
    private javax.swing.JPanel Pn_Sidebar;
    private javax.swing.JPanel Pn_menu;
    private javax.swing.JPanel Pn_utama;
    private javax.swing.JToggleButton SPL;
    private javax.swing.JToggleButton Transpose;
    private javax.swing.JToggleButton balikan;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    

   
}
